sudo: required
services:
- docker
language: python
python:
- '2.7'
script: nosetests
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: JWha5jBoHJCLRWlGLaVEZwXdCE4kVILWmKtASQ9aVEvb5NGuFlGHl2ADKDHBmWhEJqddzSDf9iu5JePLVv1UDDy+zLFObjwqZKg00d5KxyexLqRie/Z3tbTW/93PnXZwQxKV/F5xbq7rNFzU5jZ4x9J8lIWgmcJknIuiFqP9IxtI20wnDKgBiM5o1E9KEmQPPYDGinjhLJ8cJ1mbbtWPGsOnQoq0VrNo6oc5EmSsEPoWFhdKdL/3z3noOJYr5cSu37fJrK/lSzSBRbY1deo4dRIWhcUiUsTRFJSVDt2G+sbkUYE0jzoM/QSWNE69DcLTV+g0+xMuus0vXEDRbRqJdEsOpt9+CJzkIB9xHiUq1BUrCOuhH6W3VW0V+Zgie41kGPeGsp6PJ/lI6ECvP5qc8mP78JAE+VtdHK0DkKxFywnvGIZRanXLQ56h3vcWm0cn1ctKc/Lm7/yaNMuMc3G4cF1U1J5MrlmdFaO2NQjyNS3/RDtDPGd+SKRMJfMVUMcWOhvwvjDDTWhws31U2Caz0VK2YesTeBccY5LqZEKd31+UMy4FlS5udA6ZCupk66tLLoNnMk5LwEpVh2IZnDv/p8f2npIg74VRF+IjN0s8XN+2pstvhK6oleYhzkJ8UgoVSlJ9f3Fp9HT1vbsTzNDmb73aRAItzi3VLLODb4nJmt4=
  - secure: rqx02SWK17gJT2ckUdhn+TffR94W18WuZi00vfbf9eoJa8wh06PY5QX+TXDtTV7N/fzkekw/oKStl5sbiQOOoezummuseC85IItuzvY5Ubgaey9CP3wYbU6EWcwVwraK3/KxmY7nC/ysHFbEnvwcdpxaXvcUd76rt4ev03YuSXpo7g/t/i1x+8Pera9mYDr1LXaSGTSwjGLYdoMdiFN9ktwLPli52wiPG9Updv8TjlCEbGiec0zABatbBXjQZNvsYtlr/ylO636xrDEufHy5N6fBOj9u2jH79SvjqsCxSRcvu2iCki9cYiou2EImmuyqlYzQy22XT8SJgSbw/cTBhLvgaJnsPXU++k1sADyHpL/fpaPl9p3KKKvZpbvvhnT/8UzE2zAet3nKc0f9/JZ5odK5LC5UJhRprQd2pyFygVEC9bbHc9K8sGa1TlosGU1Qy1zDDspQFdjdgAJYi2EzPBNcfb3q2n6AXCQVSjoHgIwmEahtRz/pmUl6L6zpbiokQCmB4LbjAu+H11JKSiUHfhV9aqwGYy+Ubo52Xzy8TBruXCiQjPLZgQbk50aBw0UQOy3ZblVTD2Aryb3/q0AeMaZ/S8k2z+7EvA1GRiyOK3jxLUjMZBJcIi3x3lHLKv0OsVtqsJKM/N9Bcvk9obh77iBzikK8dDpQbsgFPsLma8M=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=amaksimov/
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
