sudo: required
services:
- docker
language: python
python:
- '2.7'
script: nosetests
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: DwqaL0bHKDb+i2/QR2w0M6tPT1tm2+KgkV4fDvo+bWTI0FWI6Z2gnQy2jFhxVSwMsGh+iD2Uz6TYoE/f3on+8xkZ99T1CfvNWtrOedzrMtA1Nq3/vCY6vmRs0zihf3nKZYa6jre8MZvc1bzhhDYls09XDro6AojkzfWlEp+EbYUz5r5auyMEkTLZ9I7/OsATrHVPRcuh6q/1b14bCf98Nis8tDFhDFTGuPwDHnzmy4Cb75/vZXyVwAxpxadGXy9eNcQJtnYztQwSboS05hv+xSsPQVcMgrqXClaUZofA8SFcwZTo4kgElAdg31mcS6n8fJ4dQyCOxCE0s1GkSyJvXwB5gRYfR5moIvXC9Zw/t9dRMCpDv2K//8JqyzkE6ZS+qlMYvUqch6f1K7zW/QBQl0uKwEgCEknYgdowGai7YIvf6O8tu03UG4kQGhSCPcvKRcsqoqjhXrEZiKfXZAi5htXjC2HXvBWFrAWMfT0xwECokhAYyjZQRnDR6uKpoe7vKYtheR05JQWq5emea5UqQnvLIn9+ZT4YFbaepQE00B7h5N8H7LBiV8OzH5LkDwuhn/ate6dJsWqVFJ5Nvb28tkJh2vN+1WFN0n9NEUXcK8ZVYgnIuku9JneoEnekgwc/UI/9e65zGxIYEkUr2ZlMTuvJcDQHdNGQo11oa22o4qw=
  - secure: VlixM1UAkAxfL2eq662PERNci7rU5IKf082yYZVVEH/cCxeZf5E5u6ljX1005k3tVMN4qhO+bsE8cXaQqjZoj0WwtrbdYjpyze8dLGwIUime+iRFnfSFBu5/diIrgZXr+102617y6XgcwdKz7sH26M3RPceTIRGSjDSTKmo0t4uM0N6/TtEKyH89e0EPKuuTETmRLWw3q51ct/TJ7q2Zu7w+QTrp1apLAhWTQf+pgcgTuVKx7zGd8OHNUaynY07p2CIuzOOqlERvnYIz3MvUmqTSj9Gfrc6IAKZUinMhmSadX31EvSDBqetg9QGnvbhY69DuqGeUO7VNQjXR55OtDsHxXtgj9VG1FUVYm6it//TpF6kCWoTY2D9zcVI7HDifQn0lXGrqeAjrA0LHAYaxZmIVpIJ04KD0FshzxDekud6WDecGohRN7eB3rGHoppYgnC0am82F3HP2U/YwyGPtyAcM1NUxB1cJ1XBQ8LEbseH4NXFlsINH/lutCeYa80BeD4JqEfXDbpn9NE1q9ucCkQSJ7SXmlJtlxw4E4lyvIcgUChrs/BMtcqe8yhpTmacJRpzxwG8BExSqAU0Sy78tZeEhvg00b1zFZpPM6WEfdp9GIRXTHqr6vigE9C++UzZHM1IckDx3t7KZwCmrNK0blYtS+Sy4emR27yTWHltwGmI=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=amaksimov/
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
