version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # login to Docker Hub
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: |
        docker build -f Dockerfile -t amaksimov/python_data_science:$CIRCLE_BRANCH .
        docker build -f Dockerfile.anaconda -t amaksimov/python_data_science:anaconda .

     # deploy the image
     - run: |
        docker push amaksimov/python_data_science:$CIRCLE_BRANCH
        docker push amaksimov/python_data_science:anaconda